name: Publish Docker Release and Update Brew
on:
  workflow_dispatch:
    inputs:
      release:
        description: "The name of the released version to publish"
        required: true

env:
  STEAMPIPE_VERSION: ${{ github.event.inputs.release }}
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  GH_PUBLISH_ACCESS_TOKEN: ${{ secrets.GH_PUBLISH_ACCESS_TOKEN }}

jobs:
  publish_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PUBLISH_ACCESS_TOKEN }}

      - name: Clean Version for Tag
        id: generate_docker_tag
        run: |
          echo "docker_tag=${STEAMPIPE_VERSION#"v"}" >> $GITHUB_OUTPUT

      - name: Build and Push to DockerHub and Container Registry
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          build-args: |
            TARGETVERSION=${{ env.STEAMPIPE_VERSION }}
          tags: |
            ghcr.io/tanapoln/steampipe:${{ steps.generate_docker_tag.outputs.docker_tag }}
            ghcr.io/tanapoln/steampipe:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}